### ISSUE TITLE
Canonical url is borked

### ISSUE THREAD

**Issue by sivakumar-kailasam** [ember-learn/tutorial-app#42]
<img width="575" alt="screenshot 2018-11-12 11 16 09" src="https://user-images.githubusercontent.com/604117/48328960-99715d00-e66c-11e8-9dc3-28d32dba7c5a.png">

**Comment by mansona** [comment]
This has been fixed as part of the work to make this into a "single repo system" https://github.com/ember-learn/tutorial-source/pull/5 👍
